# Application
spring.application.name=expenseflow
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/expenseflow
spring.datasource.username=expenseuser
spring.datasource.password=expensepass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.yourname.expenseflow=DEBUG