# Application
spring.application.name=expenseflow
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/expenseflow
spring.datasource.username=expenseuser
spring.datasource.password=expensepass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.gyanbiswal.expenseflow=DEBUG

# JWT Configuration
# Secret must be at least 256 bits (32 characters) for HS256 algorithm
jwt.secret=expenseflow-super-secret-key-for-jwt-signing-2024
jwt.expiration=86400000
# 86400000 ms = 24 hours

# Enables ?page=0&size=10&sort=field,direction query params
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100